DEVICE_ID = "EDGE_NODE_01"

TEMP_WARNING = 70
TEMP_CRITICAL = 85

VIBRATION_WARNING = 5
VIBRATION_CRITICAL = 8

PRESSURE_WARNING = 3
PRESSURE_CRITICAL = 2

HUMIDITY_WARNING = 80

LOG_FILE = "data/sensor_log.csv"